CREATE TABLE PAYS (
        PAYS_ID INTEGER NOT NULL,
        PAYS_NOM VARCHAR(20) NOT NULL,
        CAPITALE VARCHAR(20) NOT NULL,
        PRIMARY KEY (PAYS_ID, PAYS_NOM, CAPITALE)
);

INSERT INTO PAYS VALUES ('FRANCE', 'PARIS');